# Generated by Django 5.2.1 on 2025-06-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_parent_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='read',
        ),
    ]
