version: '3.8'

services:
  messaging_db:
    image: mysql:8.0
    container_name: messaging_db
    environment:
      MYSQL_DATABASE: messaging_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  messaging_app:
    build: .
    container_name: messaging_app
    depends_on:
      - messaging_db
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DB=messaging_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=messaging_db
    volumes:
      - .:/app

volumes:
  mysql_data:
