apiVersion: v1
kind: Service
metadata:
  name: messaging-db
spec:
  ports:
    - port: 3306
  selector:
    app: messaging-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-db
spec:
  selector:
    matchLabels:
      app: messaging-db
  replicas: 1
  template:
    metadata:
      labels:
        app: messaging-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: messaging
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
